apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: mysql-status
  namespace: mysql
spec:
  groups:
  - name: access_alert
    rules:
    - alert: MysqlStatus
      expr: mysql_up{job="mysqld-exporter"} != 1
      for: 1m
      labels:
        severity: critical



